oxr:
  url:
    api: https://openexchangerates.org/api
    historical: historical/:date.json
    latest: latest.json
  id: 8dfd323903c44132906629bdc59a7da2
  base: USD
  symbol: RUB
  timespan: 2

giphy:
  url:
    api: https://api.giphy.com/v1/gifs
  id: V3cOV6JJr9bZFx4DvyLt8f0e7WLrBzIb
  type: random
  rating: pg-13

local:
  url:
    start: http://localhost:8080/
    root: /
    fetch: /fetch
    redirect-to-fetch: redirect:/fetch/oxr

app:
  mode: auto
